const EnigmaMachine = require('../build/index');

const enigmaConf = {
  rotors: [
    {
      rotation: 3,
      connectionMap: {
        a: 'c',
        b: 'm',
        c: 'u',
        d: 'h',
        e: 'j',
        f: 'y',
        g: 'b',
        h: 'e',
        i: 'x',
        j: 'q',
        k: 'k',
        l: 'a',
        m: 't',
        n: 'd',
        o: 's',
        p: 'o',
        q: 'g',
        r: 'f',
        s: 'n',
        t: 'r',
        u: 'v',
        v: 'i',
        w: 'l',
        x: 'w',
        y: 'p',
        z: 'z'
      }
    },
    {
      rotation: 17,
      connectionMap: {
        a: 'h',
        b: 'p',
        c: 'b',
        d: 'l',
        e: 'f',
        f: 'j',
        g: 'o',
        h: 'w',
        i: 'd',
        j: 'v',
        k: 'g',
        l: 'm',
        m: 'y',
        n: 's',
        o: 't',
        p: 'r',
        q: 'a',
        r: 'n',
        s: 'z',
        t: 'e',
        u: 'u',
        v: 'c',
        w: 'k',
        x: 'q',
        y: 'i',
        z: 'x'
      }
    },
    {
      rotation: 19,
      connectionMap: {
        a: 'm',
        b: 'n',
        c: 'l',
        d: 'b',
        e: 'f',
        f: 'c',
        g: 'j',
        h: 'd',
        i: 's',
        j: 'y',
        k: 'o',
        l: 'u',
        m: 't',
        n: 'r',
        o: 'q',
        p: 'z',
        q: 'i',
        r: 'e',
        s: 'a',
        t: 'h',
        u: 'g',
        v: 'x',
        w: 'p',
        x: 'k',
        y: 'v',
        z: 'w'
      }
    }
  ],
  reflector: {
    a: 'u',
    b: 's',
    c: 'z',
    d: 'p',
    e: 'o',
    f: 'i',
    g: 'n',
    h: 'j',
    i: 'f',
    j: 'h',
    k: 'x',
    l: 'q',
    m: 'v',
    n: 'g',
    o: 'e',
    p: 'd',
    q: 'l',
    r: 't',
    s: 'b',
    t: 'r',
    u: 'a',
    v: 'm',
    w: 'y',
    x: 'k',
    y: 'w',
    z: 'c'
  },
  plugboard: {
    a: 'i',
    b: 'f',
    c: 'w',
    d: 's',
    e: 'r',
    f: 'b',
    g: 'x',
    h: 'v',
    i: 'a',
    j: 'p',
    k: 'n',
    l: 'q',
    m: 'z',
    n: 'k',
    o: 'y',
    p: 'j',
    q: 'l',
    r: 'e',
    s: 'd',
    t: 'u',
    u: 't',
    v: 'h',
    w: 'c',
    x: 'g',
    y: 'o',
    z: 'm'
  }
}
const dumbJs = {
  rotors: [
    {
      rotation: 3,
      connectionMap: {
        a: 'c',
        b: 'm',
        c: 'u',
        d: 'h',
        e: 'j',
        f: 'y',
        g: 'b',
        h: 'e',
        i: 'x',
        j: 'q',
        k: 'k',
        l: 'a',
        m: 't',
        n: 'd',
        o: 's',
        p: 'o',
        q: 'g',
        r: 'f',
        s: 'n',
        t: 'r',
        u: 'v',
        v: 'i',
        w: 'l',
        x: 'w',
        y: 'p',
        z: 'z'
      }
    },
    {
      rotation: 17,
      connectionMap: {
        a: 'h',
        b: 'p',
        c: 'b',
        d: 'l',
        e: 'f',
        f: 'j',
        g: 'o',
        h: 'w',
        i: 'd',
        j: 'v',
        k: 'g',
        l: 'm',
        m: 'y',
        n: 's',
        o: 't',
        p: 'r',
        q: 'a',
        r: 'n',
        s: 'z',
        t: 'e',
        u: 'u',
        v: 'c',
        w: 'k',
        x: 'q',
        y: 'i',
        z: 'x'
      }
    },
    {
      rotation: 19,
      connectionMap: {
        a: 'm',
        b: 'n',
        c: 'l',
        d: 'b',
        e: 'f',
        f: 'c',
        g: 'j',
        h: 'd',
        i: 's',
        j: 'y',
        k: 'o',
        l: 'u',
        m: 't',
        n: 'r',
        o: 'q',
        p: 'z',
        q: 'i',
        r: 'e',
        s: 'a',
        t: 'h',
        u: 'g',
        v: 'x',
        w: 'p',
        x: 'k',
        y: 'v',
        z: 'w'
      }
    }
  ],
  reflector: {
    a: 'u',
    b: 's',
    c: 'z',
    d: 'p',
    e: 'o',
    f: 'i',
    g: 'n',
    h: 'j',
    i: 'f',
    j: 'h',
    k: 'x',
    l: 'q',
    m: 'v',
    n: 'g',
    o: 'e',
    p: 'd',
    q: 'l',
    r: 't',
    s: 'b',
    t: 'r',
    u: 'a',
    v: 'm',
    w: 'y',
    x: 'k',
    y: 'w',
    z: 'c'
  },
  plugboard: {
    a: 'i',
    b: 'f',
    c: 'w',
    d: 's',
    e: 'r',
    f: 'b',
    g: 'x',
    h: 'v',
    i: 'a',
    j: 'p',
    k: 'n',
    l: 'q',
    m: 'z',
    n: 'k',
    o: 'y',
    p: 'j',
    q: 'l',
    r: 'e',
    s: 'd',
    t: 'u',
    u: 't',
    v: 'h',
    w: 'c',
    x: 'g',
    y: 'o',
    z: 'm'
  }
}
const enigma1 = EnigmaMachine.Enigma.generateFromEnigmaConfig(enigmaConf);
const enigma2 = EnigmaMachine.Enigma.generateFromEnigmaConfig(dumbJs);

let encrypted = enigma1.calculateString('hellothere');
console.log(encrypted);
console.log(enigma2.calculateString(encrypted));